import { BiHash, BiLinkExternal } from 'react-icons/bi';
import { FaArrowRight, FaGoogle, FaRandom, FaUserSecret } from 'react-icons/fa';
import { HiCube } from 'react-icons/hi';
import { useStep2 } from '../../hooks/steps/useStep2';

interface Step2Props {
    onNext: () => void;
}

const Step2 = ({ onNext }: Step2Props) => {
    const { proceedButton } = useStep2(onNext);

    return (
        <div className="space-y-6">
            <div className="text-center space-y-4">
                <div className="flex items-center justify-center gap-2 mb-4">
                    <BiLinkExternal className="text-3xl text-[var(--accent)]" />
                    <h2 className="text-3xl font-bold text-[var(--text-primary)]">Step 2: OAuth Login & JWT Generation</h2>
                </div>
                <p className="text-[var(--text-secondary)] text-lg max-w-2xl mx-auto">
                    The user initiates OAuth flow with their preferred provider.
                </p>
            </div>

            <div className="bg-[var(--gradient-card)] rounded-2xl p-8 border border-[var(--border)]">
                <div className="space-y-6">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-[var(--accent)] bg-opacity-20 rounded-full">
                            <BiLinkExternal className="text-2xl" />
                        </div>
                        <h3 className="text-xl font-bold text-[var(--text-primary)]">OAuth Login & JWT Generation</h3>
                    </div>

                    <p className="text-[var(--text-secondary)] mb-6 text-justify">

                        Once authenticated, the OAuth provider returns a <b>JWT (JSON Web Token)</b> containing the user's identity information.<br /><br />

                        The zkLogin address is then derived deterministically from the JWT claims (sub, iss, aud) which are obtained from the OAuth provider.<br /> This ensures the same user always gets the same address.
                    </p>

                    {/* Identity Structure Grid */}
                    <div className="mb-6">
                        <h4 className="font-semibold text-[var(--text-primary)] mb-3 flex items-center gap-2">
                            <HiCube className="text-[var(--accent)]" />
                            OAuth JWT Structure Components
                        </h4>
                        <div className="grid grid-cols-2 gap-3 mb-4">

                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <BiHash className="text-[var(--warning)]" />
                                    <span className="font-semibold text-sm">Nonce</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">Random value for address uniqueness</p>
                                <p className="text-xs text-[var(--text-secondary)]">Should be the same nonce as the one passed generated by the ephemeral key. If a mismatch is detected, the ZKProof won't be valid.</p>
                            </div>
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <FaUserSecret className="text-[var(--success)]" />
                                    <span className="font-semibold text-sm">Subject (sub)</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">Unique identifier for the specific user from JWT</p>
                                <p className="text-xs text-[var(--text-secondary)]">Stable ID that never changes for this user (e.g. "1234567890")</p>
                            </div>
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <FaGoogle className="text-[var(--accent)]" />
                                    <span className="font-semibold text-sm">Issuer (iss)</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">Identifies the OAuth provider</p>
                                <p className="text-xs text-[var(--text-secondary)]">The provider that issued the JWT (e.g. "accounts.google.com")</p>
                            </div>
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <FaGoogle className="text-[var(--primary)]" />
                                    <span className="font-semibold text-sm">Audience (aud)</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">Identifies the OAuth application/client</p>
                                <p className="text-xs text-[var(--text-secondary)]">Same for all users of this app (e.g. "myapp.googleusercontent.com")</p>
                            </div>
                        </div>
                    </div>

                    <div className="text-center pt-4">
                        {proceedButton}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Step2;
