import { FaKey, FaWallet, FaCheckCircle } from 'react-icons/fa';
import { HiFingerPrint } from 'react-icons/hi';
import { useStep1 } from '../../hooks/steps/useStep1';

interface Step1Props {
    onNext: () => Promise<void>;
}

const Step1 = ({ onNext }: Step1Props) => {

    const { proceedButton } = useStep1(onNext);

    return (
        <div className="space-y-6">
            <div className="text-center space-y-4">
                <div className="flex items-center justify-center gap-2 mb-4">
                    <FaWallet className="text-3xl text-[var(--primary)]" />
                    <h2 className="text-3xl font-bold text-[var(--text-primary)]">Step 1: Ephemeral Keypair Generation</h2>
                </div>
                <p className="text-[var(--text-secondary)] text-lg max-w-2xl mx-auto">
                    A temporary key pair is generated that will be used to sign transactions. This is NOT a wallet address yet.
                </p>
            </div>

            <div className="bg-[var(--gradient-card)] rounded-2xl p-8 border border-[var(--border)]">
                <div className="space-y-6">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-[var(--primary)] bg-opacity-20 rounded-full">
                            <FaWallet className="text-2xl" />
                        </div>
                        <h3 className="text-xl font-bold text-[var(--text-primary)]">Ephemeral Keypair Generation</h3>
                    </div>
                    
                    <p className="text-[var(--text-secondary)] mb-4 text-justify">
                        An Ephemeral Keypair (Ed25519) is generated by the SDK and will act as the <b>Signer</b> for transactions.<br/><br/>
                        <b>Important:</b> This is NOT a wallet address - it's just a temporary key pair.<br/>
                        The ephemeral key does not have its own Sui address.<br/><br/>
                        It is necessary because Sui requires a valid cryptographic signature to execute transactions.<br/>
                        The Ephemeral Keypair provides this signature capability.<br/>
                        The Ephemeral Keypair will be discarded and a new one will be re-generated for each session ensuring complete security and privacy.<br/>
                        The maximum duration of the Ephemeral Keypair is determined by the Max Epoch parameter.
                    </p>
                    
                    <div className="grid grid-cols-3 gap-3 mb-6">
                        <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                            <div className="flex items-center gap-2 mb-2">
                                <FaKey className="text-[var(--primary)]" />
                                <span className="font-semibold text-sm">Private Key</span>
                            </div>
                            <p className="text-xs text-[var(--text-muted)]">32-byte secret, never leaves client</p>
                        </div>
                        <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                            <div className="flex items-center gap-2 mb-2">
                                <HiFingerPrint className="text-[var(--accent)]" />
                                <span className="font-semibold text-sm">Public Key</span>
                            </div>
                            <p className="text-xs text-[var(--text-muted)]">32-byte identifier for verification</p>
                        </div>
                        <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                            <div className="flex items-center gap-2 mb-2">
                                <span className="text-[var(--primary)]">🔢</span>
                                <span className="font-semibold text-sm">Nonce</span>
                            </div>
                            <p className="text-xs text-[var(--text-muted)]">Derived by Mysten's library from ephemeral key</p>
                        </div>
                    </div>

                    <div className="border-t border-[var(--border)] pt-6 mb-6">
                        <h4 className="text-lg font-semibold text-[var(--text-primary)] mb-4">Additional Configuration</h4>
                        <p className="text-[var(--text-secondary)] mb-4 text-sm">
                            These parameters will also be configured for the zkLogin flow:
                        </p>
                        
                        <div className="grid grid-cols-1 gap-3">
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <span className="text-[var(--primary)]">🌐</span>
                                    <span className="font-semibold text-sm">Network</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)]">Sui network to connect to (testnet/mainnet). Determines which blockchain your transactions will be submitted to.</p>
                            </div>
                            
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <span className="text-[var(--accent)]">⏰</span>
                                    <span className="font-semibold text-sm">Max Epoch</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)]">Maximum epoch duration for ephemeral key validity. Defines how long your session key remains active before expiring.</p>
                            </div>
                            
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <span className="text-[var(--primary)]">🧂</span>
                                    <span className="font-semibold text-sm">Salt</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)]">Random value used in address derivation. Ensures your zkLogin address is unique and unpredictable, even with the same OAuth provider.</p>
                            </div>
                        </div>
                    </div>
                    
                    <div className="flex items-center gap-2 text-[var(--primary)] text-sm font-medium mb-6">
                        <FaCheckCircle />
                        <span>Ephemeral & Session-based</span>
                    </div>

                    <div className="text-center pt-4">
                        {proceedButton}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Step1;
