import { FaLock, FaCog, FaCode, FaDatabase, FaServer, FaCloud, FaDocker } from 'react-icons/fa';
import { useStep3 } from '../../hooks/steps/useStep3';

interface Step3Props {
    onNext: () => void;
}

const Step3 = ({ onNext }: Step3Props) => {
    const { proceedButton, error } = useStep3(onNext);

    return (
        <div className="space-y-6">
            <div className="text-center space-y-4">
                <div className="flex items-center justify-center gap-2 mb-4">
                    <FaLock className="text-3xl text-[var(--success)]" />
                    <h2 className="text-3xl font-bold text-[var(--text-primary)]">Step 3: ZK Proof Verification & Wallet Generation</h2>
                </div>
                <p className="text-[var(--text-secondary)] text-lg max-w-2xl mx-auto">
                    This is where the magic happens! Generate a zero-knowledge proof that demonstrates you own a valid JWT without revealing any personal information.
                </p>
            </div>

            <div className="bg-[var(--gradient-card)] rounded-2xl p-8 border border-[var(--border)]">
                <div className="space-y-6">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-[var(--success)] bg-opacity-20 rounded-full">
                            <FaLock className="text-2xl" />
                        </div>
                        <h3 className="text-xl font-bold text-[var(--text-primary)]">Zero-Knowledge Proof Generation & Wallet Generation</h3>
                    </div>
                    
                    <p className="text-[var(--text-secondary)] mb-6 text-justify">
                        A <b>zero-knowledge proof</b> is generated by the prover, that demonstrates the user owns a valid JWT from the OAuth provider without revealing any personal information.<br/><br/>
                        
                        The ZK circuit takes the JWT and proves two critical things: <b>(1)</b> The JWT signature is valid (proving it came from the real OAuth provider), and <b>(2)</b> The nonce in the JWT matches the nonce derived from the ephemeral public key.<br/><br/>
                        
                    </p>
                    
                    <div className="mb-4">
                        <h4 className="font-semibold text-[var(--text-primary)] mb-3 flex items-center gap-2">
                            <FaCog className="text-[var(--success)]" />
                            ZK Circuit Components
                        </h4>
                        <div className="grid grid-cols-2 gap-3">
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <FaCode className="text-[var(--primary)]" />
                                    <span className="font-semibold text-sm">JWT Verification</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">Proves JWT signature validity without revealing content</p>
                                <p className="text-xs text-[var(--text-secondary)]">Verifies RSA/ECDSA signature from OAuth provider using public keys</p>
                            </div>
                            <div className="bg-[var(--bg-tertiary)] p-3 rounded-lg">
                                <div className="flex items-center gap-2 mb-2">
                                    <FaDatabase className="text-[var(--accent)]" />
                                    <span className="font-semibold text-sm">Nonce Matching</span>
                                </div>
                                <p className="text-xs text-[var(--text-muted)] mb-2">Ensures nonce in JWT matches ephemeral key commitment</p>
                                <p className="text-xs text-[var(--text-secondary)]">Prevents man-in-the-middle attacks and session hijacking</p>
                            </div>
                        </div>
                    </div>

                    {/* Prover Service Section */}
                    <div className="mb-6">
                        <h4 className="font-semibold text-[var(--text-primary)] mb-3 flex items-center gap-2">
                            <FaServer className="text-[var(--warning)]" />
                            Prover Service Required
                        </h4>
                        <div className="bg-[var(--bg-tertiary)] p-4 rounded-lg">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <h5 className="font-semibold text-[var(--text-primary)] mb-2 flex items-center gap-2">
                                        <FaCloud className="text-[var(--accent)]" />
                                        Mysten Labs (Hosted)
                                    </h5>
                                    <p className="text-xs text-[var(--text-muted)] mb-2">
                                        <code className="bg-[var(--bg-secondary)] px-2 py-1 rounded text-[var(--accent)]">prover-dev.mystenlabs.com</code>
                                    </p>
                                    <p className="text-xs text-[var(--text-secondary)]">Free for development/testing on Devnet</p>
                                </div>
                                <div>
                                    <h5 className="font-semibold text-[var(--text-primary)] mb-2 flex items-center gap-2">
                                        <FaDocker className="text-[var(--primary)]" />
                                        Self-Hosted
                                    </h5>
                                    <p className="text-xs text-[var(--text-muted)] mb-2">Deploy your own using Docker images</p>
                                    <p className="text-xs text-[var(--text-secondary)]">Full control, production-ready setup</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="text-center pt-4">
                        {error && (
                            <p className="text-sm text-red-500 mb-3">{error}</p>
                        )}
                        {proceedButton}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Step3;
